// front-end/vue/src/components/Header.vue
<template>
    <header>
        <nav
            class=" navbar navbar-fixed-top navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between container">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <RouterLink to="/" class="nav-link text-dark" active-class="active">Home</RouterLink>
                    </li>

                    <li class="nav-item">
                        <RouterLink to="/tickets" class="nav-link text-dark" active-class="active">
                            {{ identityStore.$state.jwt?.role == 'admin' ? "Tickets" : "Buy pass" }}
                        </RouterLink>
                    </li>
                    <li class="nav-item">
                        <RouterLink to="/menuItems" class="nav-link text-dark" active-class="active">
                            Menu
                        </RouterLink>
                    </li>
                    <li class="nav-item" v-if="identityStore.$state.jwt?.role == 'admin'">
                        <RouterLink to="/itemCategories" class="nav-link text-dark" active-class="active">
                            Menu categories
                        </RouterLink>
                    </li>
                    <li class="nav-item" v-if="identityStore.$state.jwt?.role == 'admin'">
                        <RouterLink to="/userCategory" class="nav-link text-dark" active-class="active">
                            User categories
                        </RouterLink>
                    </li>
                    <li class="nav-item" v-if="identityStore.$state.jwt?.role == 'admin'">
                        <RouterLink to="/couponCategory" class="nav-link text-dark" active-class="active">
                            Coupons
                        </RouterLink>
                    </li>
                     <li class="nav-item" v-if="identityStore.$state.jwt?.role == 'admin'">
                        <RouterLink to="/coordinate" class="nav-link text-dark" active-class="active">
                            Table
                        </RouterLink>
                    </li>
                    <li class="nav-item" v-if="identityStore.$state.jwt?.role == 'admin'">
                        <RouterLink to="/location" class="nav-link text-dark" active-class="active">
                            Caffe
                        </RouterLink>
                    </li>
                    <li class="nav-item" v-if="identityStore.$state.jwt?.role == 'user'">
                        <RouterLink to="/order" class="nav-link text-dark" active-class="active">Cart
                        </RouterLink>
                    </li>
                </ul>

                <ul class="navbar-nav">
                    <template v-if="identityStore.$state.jwt == null">
                        <li>
                            <RouterLink to="/register" class="nav-link text-dark" active-class="active">Register
                            </RouterLink>
                        </li>
                        <li>
                            <RouterLink to="/login" class="nav-link text-dark" active-class="active">Login
                            </RouterLink>
                        </li>
                    </template>

                    <template v-else>
                        <li class="nav-item dropdown">
                            <a class="nav-link text-dark dropdown-toggle" data-bs-toggle="dropdown" role="button"
                                aria-haspopup="true" aria-expanded="false" href="#">Hello,
                                {{ identityStore.$state.jwt?.firstName }}<span class="caret"></span></a>
                            <ul class="dropdown-menu" >
                                <li>
                                    <RouterLink to="/account" class="nav-link text-dark" active-class="active">My
                                        account
                                    </RouterLink>
                                </li>
                                <div  v-if="identityStore.$state.jwt?.role == 'user'">
                                <li>
                                    <RouterLink to="/orders" class="nav-link text-dark" active-class="active">Orders
                                    </RouterLink>
                                </li>
                                <li>
                                    <RouterLink to="/cards" class="nav-link text-dark" active-class="active">Cards
                                    </RouterLink>
                                </li>
                                <li>
                                    <RouterLink to="/ticketsInOrder" class="nav-link text-dark" active-class="active">
                                        Tickets
                                    </RouterLink>
                                </li>
                                <li>
                                    <RouterLink to="/usersCoupon" class="nav-link text-dark" active-class="active">
                                        Coupons
                                    </RouterLink>
                                </li>
                                </div>
                                <li>
                                    <RouterLink to="/login" class="nav-link text-dark" active-class="active" @click="handleLogout">
                                        Logout
                                    </RouterLink>
                                </li>
                            </ul>
                        </li>
                    </template>

                </ul>
            </div>

        </nav>
    </header>
</template>


<script lang="ts">
import { useIdentityStore } from "@/stores/identity";
import { Options, Vue } from "vue-class-component";
import { RouterLink } from "vue-router";

@Options({
    components: {
    }
})
export default class Header extends Vue {
    identityStore = useIdentityStore();


    handleLogout(): void {
        this.identityStore.$state.jwt = null;
    }
}


</script>

// front-end/react/src/components/Header.tsx
import React, { useContext } from 'react';
import { Link } from 'react-router-dom';
import { IJWTResponse } from '../domain/IJWTResponse';
import { AppContext } from '../state/AppContext';

let initialJWT: IJWTResponse = {
    token: "",
    refreshToken: "",
    firstName: "",
    lastName: "",
    email: "",
    role: ""
};

const Header = () => {

    const userRole = useContext(AppContext).jwt.role;
    const appState = useContext(AppContext);
    const handleLogout = () => {
        appState.setJwt(initialJWT);
    }

    return (
        <header>
            <nav className="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                <div className="container container-fluid">
                    <Link to="/" className="navbar-brand">Home</Link>
                    <button className="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                        <span className="navbar-toggler-icon"></span>
                    </button>
                    <div className="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul className="navbar-nav flex-grow-1">
                            <li className="nav-item">
                                <Link to="/tickets" className="nav-link text-dark">Buy pass</Link>
                            </li>
                            <li className="nav-item">
                                <Link to="/menuitems" className="nav-link text-dark">Food&Drink</Link>
                            </li>
                            {userRole == 'admin' &&
                                <li className="nav-item">
                                    <Link to="/itemcategories" className="nav-link text-dark">Categories</Link>
                                </li>
                            }

                        </ul>
                        {!userRole &&
                            <ul className="navbar-nav">
                                <li className="nav-item">
                                    <Link to="/register" className="nav-link text-dark">Register</Link>
                                </li>
                                <li className="nav-item">
                                    <Link to="/login" className="nav-link text-dark">Login</Link>
                                </li>
                            </ul>
                        }
                        {userRole &&
                            <>
                                <a className="nav-link text-dark"> Hello, {appState.jwt.firstName}! </a>
                                <Link to="/login" className="nav-link text-dark" onClick={handleLogout}>Logout</Link>
                            </>
                        }
                    </div>
                </div>
            </nav>
        </header>
    );

}

export default Header;
