// Front-end apps/react-hw/src/components/itemCategories/ItemCategoriesEdit.tsx
import React, { useContext, useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { useParams } from 'react-router-dom';
import { ItemCategoryService } from '../../services/ItemCategoryService';
import { AppContext } from '../../state/AppContext';


const ItemCategoriesEdit = () => {

    let appState = useContext(AppContext);
    let { id } = useParams();
    const itemCategoryService = new ItemCategoryService(appState);
    const [jwt, setJwt] = useState(appState.jwt);
    const [category, setItemCategory] = useState(appState.category);

    useEffect(() => {
        itemCategoryService.getById(id!).then(data => setItemCategory(data));
    }, []);

    const handleSubmit = () => {
        itemCategoryService.put(id!, category).then(data => setItemCategory(data));
    }

    const handleDelete = () => {
        itemCategoryService.delete(id!);
    }

    return (
        <>
            <h3>Edit item category</h3>
            <div className="row">
                <div className="col-md-4">
                    <div className="text-danger validation-summary-valid" data-valmsg-summary="true">
                        <ul>
                            <li ></li>
                        </ul>
                    </div>
                    <div className="form-group">
                        <label className="control-label">Ticket Name</label>
                        <input type="text" value={category.name} onChange={(e) => {

                            category.name = e.target.value;
                            appState.setJwt(jwt);
                            setItemCategory(category);
                        }} className="form-control"
                        />
                        <span
                            className="text-danger field-validation-valid"
                            data-valmsg-for="TicketName"
                            data-valmsg-replace="true"
                        ></span>
                    </div>
                    <div className="form-group">
                        <Link to="/itemcategories" className="btn btn-primary" onClick={handleSubmit}>Save</Link>
                    </div>
                    <div className="form-group">
                        <Link to="/itemcategories" className="btn btn-danger" onClick={handleDelete}>Delete</Link>
                    </div>
                    <td />
                    <Link to="/itemcategories">Back to main</Link>
                </div>
            </div>
        </>
    )
}

export default ItemCategoriesEdit;

// client/vue/src/views/itemCategories/ItemCategoriesEdit.vue
<template>
    <h3>Edit item category</h3>
    <div className="row">
        <div className="col-md-12">
            <form>
                <div className="form-group">
                    <label className="control-label">Category name </label>
                    <input type="text" className="form-control" v-model="itemCategoryName" />
                </div>

                <div class="form-group">
                    <a @click="submitClicked()" class="btn btn-primary"> Save</a>
                </div>
                <RouterLink to="/itemcategories">Back to main</RouterLink>
            </form>
        </div>
    </div>

</template>

<script lang="ts">


import router from "@/router";
import { ItemCategoryService } from "@/services/ItemCategoryService";
import { useItemCategoryStore } from "@/stores/itemCategories";
import { Options, Vue } from "vue-class-component";
@Options({
    components: {
    },
    props: {
        id: String
    },
    emits: [],
})


export default class ItemCategoriesEdit extends Vue {
    id!: string;
    itemCategoriesStore = useItemCategoryStore();
    itemCategoryService = new ItemCategoryService();
    itemCategoryName: string = "";
    errorMessage: string | null = null;
    async mounted(): Promise<void> {
        console.log("mounted");
        this.itemCategoriesStore.$state.itemCategories = [];
        this.itemCategoryName = (await this.itemCategoryService.get(this.id)).name;
    }
    async submitClicked(): Promise<void> {
        var res = await this.itemCategoryService.put(this.id, {
            id: this.id,
            name: this.itemCategoryName
        });
        if (res.status >= 300) {
                this.errorMessage = res.status + ' ' + res.errorMsg;
                alert("Please fill all the fields!")
            } else {
                this.itemCategoriesStore.$state.itemCategories =
                    await this.itemCategoryService.getAll();

                this.$router.push('/itemcategories');
            }
    }
}
</script>
