// front-end/react/src/components/itemCategories/ItemCategoriesCreate.tsx
import React, { useContext, useState } from 'react';
import { Link } from 'react-router-dom';
import { IItemCategory } from '../../domain/IItemCategory';
import { ItemCategoryService } from '../../services/ItemCategoryService';
import { AppContext } from '../../state/AppContext';

let initialCategory: IItemCategory = {
    id: "",
    name: ""
};

const ItemCategoriesCreate = () => {
    let appState = useContext(AppContext);
    const itemCategoryService = new ItemCategoryService(appState);
    const [category, setItemCategory] = useState(initialCategory);
    const [jwt, setJwt] = useState(appState.jwt);

    const handleSubmit = () => {
        itemCategoryService.create(category.name);
    }

    return (
        <>
            <h3>Create new menu item category</h3>
            <div className="row">
                <div className="col-md-12">
                    <div className="form-group">
                        <label className="control-label">Category Name</label>
                        <input type="text" className="form-control" value={category.name} onChange={(e) => {

                            category.name = e.target.value;
                            appState.setJwt(jwt);
                            setItemCategory(category);
                        }}
                        />
                    </div>
                    <div className="form-group">
                        <Link to="/itemcategories" className="btn btn-primary" onClick={handleSubmit}>Create</Link>
                    </div>
                    <Link to="/itemcategories">Back to main</Link>

                </div>
            </div>

        </>
    )
}

export default ItemCategoriesCreate;

// front-end/vue/src/views/itemCategories/ItemCategoriesCreate.vue
<template>
    <h3>Create new item category</h3>
    <div className="row">
        <div className="col-md-12">
            <form>
                <div className="form-group">
                    <label className="control-label">Category name </label>
                    <input type="text" v-model="itemCategoryName" className="form-control" />
                </div>

                <div class="form-group">
                    <a @click="submitClicked()" class="btn btn-primary">Create</a>
                </div>
                <RouterLink to="/itemcategories">Back to main</RouterLink>
            </form>
        </div>
    </div>

</template>

<script lang="ts">
import router from "@/router";
import { ItemCategoryService } from "@/services/ItemCategoryService";
import { useItemCategoryStore } from "@/stores/itemCategories";
import { Vue } from "vue-class-component";


export default class ItemCategoriesCreate extends Vue {
    itemCategoryService = new ItemCategoryService();
    itemCategoriesStore = useItemCategoryStore();
    itemCategoryName!: string;
    errorMessage: string | null = null;

    async submitClicked(): Promise<void> {
        console.log('submitClicked');
        var res = await this.itemCategoryService.add({
            name: this.itemCategoryName
        });
       if (res.status >= 300) {
                this.errorMessage = res.status + ' ' + res.errorMsg;
                alert("Please fill all the fields!")
            } else {
                this.itemCategoriesStore.$state.itemCategories =
                    await this.itemCategoryService.getAll();

                this.$router.push('/itemcategories');
            }
    }
}
</script>
