// client/vue/src/views/tickets/TicketEdit.vue
<template>
    <h3>Edit ticket</h3>
    <div className="row">
        <div className="col-md-12">
            <form>
               
                <div className="form-group">
                    <label className="control-label">Ticket name </label>
                    <input type="text" className="form-control" v-model="ticketName" />
                </div>

                
                <div className="form-group">
                    <label className="control-label">Day Range</label>
                    <input type="number" className="form-control" v-model="ticketDayRange" />
                </div>

               
                <div className="form-group">
                    <label className="control-label">Price</label>
                    <input type="number" className="form-control" v-model="ticketPrice" />
                </div>

                <div class="form-group">
                    <a @click="submitClicked()" class="btn btn-primary">Save</a>
                </div>
                <RouterLink to="/tickets">Back to main</RouterLink>
            </form>
        </div>
    </div>

</template>

<script lang="ts">
import router from "@/router";
import { TicketService } from "@/services/TicketService";
import { useTicketStore } from "@/stores/tickets";
import { Options, Vue } from "vue-class-component";

@Options({
    components: {
    },
    props: {
        id: String
    },
    emits: [],
})

export default class TicketCreate extends Vue {
    id!: string;
    ticketName: string = "";
    ticketPrice: string = "";
    ticketDayRange: string = "";
    ticketsStore = useTicketStore();
    ticketService = new TicketService();
    errorMessage: string | null = null;

    async mounted(): Promise<void> {
        console.log("mounted");
        this.ticketsStore.$state.tickets = [];
        this.ticketName = (await this.ticketService.get(this.id)).name;
        this.ticketPrice = (await this.ticketService.get(this.id)).price;
        this.ticketDayRange = (await this.ticketService.get(this.id)).dayRange;
    }

    async submitClicked(): Promise<void> {

            var res = await this.ticketService.put(this.id, {
                id: this.id,
                name: this.ticketName,
                price: this.ticketPrice,
                dayRange: this.ticketDayRange
            });

            if (res.status >= 300) {
                this.errorMessage = res.status + ' ' + res.errorMsg;
                alert("Please fill all the fields!")
            } else {
                this.ticketsStore.$state.tickets =
                    await this.ticketService.getAll();

                this.$router.push('/tickets');
            }
        } 
    }

   

</script>

// client/react/src/components/tickets/TicketEdit.tsx
import React, { useContext, useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { useParams } from 'react-router-dom';
import { ITicket } from '../../domain/ITicket';
import { TicketService } from '../../services/TicketService';
import { AppContext, AppContextProvider } from '../../state/AppContext';


const TicketEdit = () => {
    let { id } = useParams();
    const appState = useContext(AppContext);
    console.log("a[s");
    console.log(appState.jwt);
    const ticketService = new TicketService(appState);
    const [jwt, setJwt] = useState(appState.jwt);
    let [ticket, setTicket] = useState(appState.ticket);


    useEffect(() => {
        ticketService.getById(id!).then(data => setTicket(data));
    }, []);

    const handleDelete = () => {
        console.log("appstat");
        console.log(appState.jwt);
        ticketService.delete(id!);
    }

    const handleSubmit = () => {
        console.log("appState.jwt");
        ticketService.put(id!, ticket).then(data => setTicket(data));
    }

    return (
        <>
            <h3>Edit ticket</h3>
            <div className="row">
                <div className="col-md-4">

                    <div className="form-group">
                        <label className="control-label">Ticket Name</label>
                        <input type="text" value={ticket.name} onChange={(e) => {
                            ticket.name = e.target.value;
                            appState.setJwt(jwt);
                            setTicket(ticket);

                        }} className="form-control"
                        />

                    </div>
                    <div className="form-group">
                        <label className="control-label">Day Range</label>
                        <input type="number" value={ticket.dayRange} onChange={(e) => {
                            ticket.dayRange = e.target.value;
                            appState.setJwt(jwt);
                            setTicket(ticket);
                        }} className="form-control"
                        />
                    </div>
                    <div className="form-group">
                        <label className="control-label">Price</label>
                        <input type="number" value={ticket.price} onChange={(e) => {
                            appState.setJwt(jwt);
                            ticket.price = e.target.value;
                            setTicket(ticket);
                        }} className="form-control"
                        />

                    </div>
                    <div className="form-group">
                        <Link to="/tickets" className="btn btn-primary" onClick={handleSubmit}>Save</Link>
                    </div>
                    <div className="form-group">

                        <Link to="/tickets" className="btn btn-danger" onClick={handleDelete}>Delete</Link>
                    </div>

                    <td />
                    <Link to="/tickets">Back to main</Link>
                </div>
            </div>
        </>
    )
}

export default TicketEdit;
